package com.company.traceuploader.state;

import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;

public class JsonlWalUploadStateStore implements UploadStateStore {
    private final Path walPath; private final Map<String,UploadFileRecord> records=new LinkedHashMap<>();
    public JsonlWalUploadStateStore(Path walPath) throws IOException { this.walPath=walPath; Files.createDirectories(walPath.getParent()); if(Files.exists(walPath)) load(); }
    private void load() throws IOException { try(BufferedReader br=Files.newBufferedReader(walPath, StandardCharsets.UTF_8)){String line; while((line=br.readLine())!=null){ if(line.isBlank()) continue; UploadFileRecord r=decode(line); records.put(r.fileId, r); } } }
    public synchronized void upsert(UploadFileRecord record) throws IOException { long now=System.currentTimeMillis(); UploadFileRecord old=records.get(record.fileId); if(old!=null && old.firstSeenTimeMs>0) record.firstSeenTimeMs=old.firstSeenTimeMs; if(record.firstSeenTimeMs==0) record.firstSeenTimeMs=now; record.lastUpdateTimeMs=now; records.put(record.fileId, copy(record)); append(record); }
    public synchronized void updateState(String fileId, UploadState state, String error) throws IOException { UploadFileRecord r=records.get(fileId); if(r==null) throw new IllegalArgumentException("Unknown file_id: "+fileId); r.state=state; r.lastError=error; r.lastUpdateTimeMs=System.currentTimeMillis(); if(state==UploadState.UPLOADING) r.attempt++; append(r); }
    public synchronized Optional<UploadFileRecord> getByFileId(String fileId){ UploadFileRecord r=records.get(fileId); return r==null?Optional.empty():Optional.of(copy(r)); }
    public synchronized List<UploadFileRecord> findPending(int limit){ return records.values().stream().filter(r -> r.state != UploadState.MANIFEST_COMMITTED && r.state != UploadState.LOCAL_GC_READY && r.state != UploadState.LOCAL_GC_DONE && r.state != UploadState.QUARANTINED && r.state != UploadState.PERMANENT_FAILED).limit(limit).map(this::copy).toList(); }
    private void append(UploadFileRecord r) throws IOException { Files.createDirectories(walPath.getParent()); try(BufferedWriter bw=Files.newBufferedWriter(walPath, StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.APPEND)){ bw.write(encode(r)); bw.newLine(); } }
    private static String encode(UploadFileRecord r){ return String.join("\t", esc(r.fileId),esc(r.app),esc(r.env),esc(r.region),esc(r.cluster),esc(r.host),esc(r.pid),esc(r.bootId),esc(r.localPath),esc(r.donePath),esc(r.hdfsStagingPath),esc(r.hdfsFinalPath),esc(r.dt),String.valueOf(r.hour),String.valueOf(r.bucket),String.valueOf(r.startTimeMs),String.valueOf(r.endTimeMs),String.valueOf(r.sizeBytes),esc(r.checksum),String.valueOf(r.recordCount),r.state==null?"":r.state.name(),String.valueOf(r.attempt),String.valueOf(r.firstSeenTimeMs),String.valueOf(r.lastUpdateTimeMs),String.valueOf(r.nextRetryTimeMs),esc(r.lastError)); }
    private static UploadFileRecord decode(String line){ String[] a=line.split("\t",-1); UploadFileRecord r=new UploadFileRecord(); int i=0; r.fileId=un(a,i++); r.app=un(a,i++); r.env=un(a,i++); r.region=un(a,i++); r.cluster=un(a,i++); r.host=un(a,i++); r.pid=un(a,i++); r.bootId=un(a,i++); r.localPath=un(a,i++); r.donePath=un(a,i++); r.hdfsStagingPath=un(a,i++); r.hdfsFinalPath=un(a,i++); r.dt=un(a,i++); r.hour=pi(a,i++); r.bucket=pi(a,i++); r.startTimeMs=pl(a,i++); r.endTimeMs=pl(a,i++); r.sizeBytes=pl(a,i++); r.checksum=un(a,i++); r.recordCount=pl(a,i++); String st=un(a,i++); r.state=st.isBlank()?null:UploadState.valueOf(st); r.attempt=pi(a,i++); r.firstSeenTimeMs=pl(a,i++); r.lastUpdateTimeMs=pl(a,i++); r.nextRetryTimeMs=pl(a,i++); r.lastError=un(a,i); return r; }
    private static String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\t","\\t").replace("\n","\\n");} private static String un(String[] a,int i){return i>=a.length?"":a[i].replace("\\n","\n").replace("\\t","\t").replace("\\\\","\\");} private static int pi(String[]a,int i){return i>=a.length||a[i].isBlank()?0:Integer.parseInt(a[i]);} private static long pl(String[]a,int i){return i>=a.length||a[i].isBlank()?0:Long.parseLong(a[i]);}
    private UploadFileRecord copy(UploadFileRecord r){ return decode(encode(r)); }
    public void close() {}
}
