package com.company.traceuploader.state;
public enum UploadState { DISCOVERED, SEALED, CHECKSUMED, UPLOADING, UPLOADED_TO_STAGING, VERIFYING, RENAMING, COMMITTED_TO_HDFS, MANIFEST_COMMITTED, LOCAL_GC_READY, LOCAL_GC_DONE, RETRYABLE_FAILED, PERMANENT_FAILED, QUARANTINED }
